// Code generated by protoc-gen-go.
// source: event.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	event.proto

It has these top-level messages:
	Event
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	// Unique ID of the event.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The time given by the source producer of the event.
	// This can be manually set in code, otherwise it will be
	// set by the client producing the event.
	Time int64 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	// Acknowledged timestamp of the event. This is provided by the backend,
	// but a field is here if the event is republished as-is.
	AckTime int64 `protobuf:"varint,11,opt,name=ack_time,json=ackTime" json:"ack_time,omitempty"`
	// The event type.
	Type string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	// An optional event ID that is the cause of this event.
	Cause string `protobuf:"bytes,5,opt,name=cause" json:"cause,omitempty"`
	// The client that produced this event.
	Client string `protobuf:"bytes,6,opt,name=client" json:"client,omitempty"`
	// Schema is the name of the schema of the encoded data.
	// This will likely be a name and optionally a version suffix.
	Schema string `protobuf:"bytes,4,opt,name=schema" json:"schema,omitempty"`
	// Encoding of the event data.
	Encoding string `protobuf:"bytes,8,opt,name=encoding" json:"encoding,omitempty"`
	// Encoded event data.
	Data []byte `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	// Arbitrary metadata as a set of key-value pairs. This can be used
	// for adding upstream user/client info, authorization tokens, etc.
	Meta map[string]string `protobuf:"bytes,10,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Key of the "aggregate" that this event is about.
	Aggregate string `protobuf:"bytes,12,opt,name=aggregate" json:"aggregate,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetAckTime() int64 {
	if m != nil {
		return m.AckTime
	}
	return 0
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *Event) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

func (m *Event) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Event) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Event) GetAggregate() string {
	if m != nil {
		return m.Aggregate
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x3d, 0x4f, 0xf3, 0x40,
	0x0c, 0xc7, 0x95, 0xcb, 0x4b, 0x13, 0xa7, 0x7a, 0xf4, 0xc8, 0x20, 0x74, 0x54, 0x0c, 0x11, 0x0b,
	0x99, 0x32, 0xc0, 0x00, 0x62, 0xef, 0xc8, 0x12, 0xb1, 0x23, 0xe7, 0x62, 0x85, 0x28, 0xcd, 0x8b,
	0xd2, 0x6b, 0xa5, 0x7c, 0x4b, 0x3e, 0x12, 0x3a, 0xa7, 0x2a, 0xdb, 0xff, 0xf7, 0xb3, 0xcf, 0x27,
	0x1b, 0x52, 0x3e, 0xf3, 0x60, 0x8b, 0x69, 0x1e, 0xed, 0x88, 0x6a, 0xaa, 0x1e, 0x7f, 0x14, 0x84,
	0x7b, 0xe7, 0xf0, 0x1f, 0xa8, 0xb6, 0xd6, 0x5e, 0xe6, 0xe5, 0x49, 0xa9, 0xda, 0x1a, 0x11, 0x02,
	0xdb, 0xf6, 0xac, 0x55, 0xe6, 0xe5, 0x7e, 0x29, 0x19, 0xef, 0x21, 0x26, 0xd3, 0x7d, 0x89, 0x4f,
	0xc5, 0x6f, 0xc8, 0x74, 0x9f, 0xae, 0xe4, 0xda, 0x97, 0x89, 0xb5, 0x2f, 0x03, 0x24, 0xe3, 0x2d,
	0x84, 0x86, 0x4e, 0x47, 0xd6, 0xa1, 0xc8, 0x15, 0xf0, 0x0e, 0x22, 0x73, 0x68, 0x79, 0xb0, 0x3a,
	0x12, 0x7d, 0x21, 0xe7, 0x8f, 0xe6, 0x9b, 0x7b, 0xd2, 0xc1, 0xea, 0x57, 0xc2, 0x1d, 0xc4, 0x3c,
	0x98, 0xb1, 0x6e, 0x87, 0x46, 0xc7, 0x52, 0xb9, 0xb2, 0xfb, 0xb5, 0x26, 0x4b, 0x7a, 0x93, 0x79,
	0xf9, 0xb6, 0x94, 0x8c, 0x4f, 0x10, 0xf4, 0x6c, 0x49, 0x43, 0xe6, 0xe7, 0xe9, 0xf3, 0x4d, 0x31,
	0x55, 0x85, 0x6c, 0x58, 0x7c, 0xb0, 0xa5, 0xfd, 0x60, 0xe7, 0xa5, 0x94, 0x06, 0x7c, 0x80, 0x84,
	0x9a, 0x66, 0xe6, 0x86, 0x2c, 0xeb, 0xad, 0x4c, 0xfe, 0x13, 0xbb, 0x57, 0x48, 0xae, 0x0f, 0xf0,
	0x3f, 0xf8, 0x1d, 0x2f, 0x97, 0xeb, 0xb8, 0xe8, 0x76, 0x3b, 0xd3, 0xe1, 0xb4, 0xde, 0x27, 0x29,
	0x57, 0x78, 0x57, 0x6f, 0x5e, 0x15, 0xc9, 0x75, 0x5f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xdb,
	0x37, 0x6a, 0xeb, 0x6c, 0x01, 0x00, 0x00,
}
